### PR TITLE
Fix failing test and enable NumPy 2.0

### LINKED ISSUE #26: Errors on the number of waves?
Some errors were observed locally during the update for #25, but not on the action tests. More investigation is needed.

```
======================================= FAILURES ========================================
____________ TestPeriodicControlFunction.test_number_of_waves[100-triangle] _____________

self = <test_control_pulseoptim.TestPeriodicControlFunction object at 0x7f7808e7d590>
pulse_type = 'TRIANGLE', n_waves = 100

    @pytest.mark.parametrize("n_waves", [1, 5, 10, 100])
    def test_number_of_waves(self, pulse_type, n_waves):
        kwargs = {
            "num_tslots": self.num_tslots,
            "evo_time": self.evo_time,
            "init_pulse_type": pulse_type,
            "init_pulse_params": {"num_waves": n_waves},
            "gen_stats": False,
        }
        system = _merge_kwargs(hadamard, kwargs)
>       assert _count_waves(system) == n_waves
E       AssertionError: assert np.int64(98) == 100
E        +  where np.int64(98) = _count_waves(_System(system=Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True\nQobj data =\n[[ 1.  0...se, 'init_pulse_type': 'TRIANGLE', 'fid_err_targ': 1e-10, 'dyn_type': 'UNIT', 'init_pulse_params': {'num_waves': 100}}))

tests/test_control_pulseoptim.py:626: AssertionError
________________ TestPeriodicControlFunction.test_frequency[10-triangle] ________________

self = <test_control_pulseoptim.TestPeriodicControlFunction object at 0x7f7808e89810>
pulse_type = 'TRIANGLE', frequency = 10

    @pytest.mark.parametrize("frequency", [0.1, 1, 10, 20])
    def test_frequency(self, pulse_type, frequency):
        kwargs = {
            "num_tslots": self.num_tslots,
            "evo_time": self.evo_time,
            "init_pulse_type": pulse_type,
            "init_pulse_params": {"freq": frequency},
            "fid_err_targ": 1e-5,
            "gen_stats": False,
        }
        system = _merge_kwargs(hadamard, kwargs)
>       assert _count_waves(system) == self.evo_time * frequency
E       AssertionError: assert np.int64(98) == (10 * 10)
E        +  where np.int64(98) = _count_waves(_System(system=Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True\nQobj data =\n[[ 1.  0...': False, 'init_pulse_type': 'TRIANGLE', 'fid_err_targ': 1e-05, 'dyn_type': 'UNIT', 'init_pulse_params': {'freq': 10}}))
E        +  and   10 = <test_control_pulseoptim.TestPeriodicControlFunction object at 0x7f7808e89810>.evo_time

tests/test_control_pulseoptim.py:639: AssertionError
________________ TestPeriodicControlFunction.test_frequency[20-triangle] ________________

self = <test_control_pulseoptim.TestPeriodicControlFunction object at 0x7f7808e8a510>
pulse_type = 'TRIANGLE', frequency = 20

    @pytest.mark.parametrize("frequency", [0.1, 1, 10, 20])
    def test_frequency(self, pulse_type, frequency):
        kwargs = {
            "num_tslots": self.num_tslots,
            "evo_time": self.evo_time,
            "init_pulse_type": pulse_type,
            "init_pulse_params": {"freq": frequency},
            "fid_err_targ": 1e-5,
            "gen_stats": False,
        }
        system = _merge_kwargs(hadamard, kwargs)
>       assert _count_waves(system) == self.evo_time * frequency
E       AssertionError: assert np.int64(198) == (10 * 20)
E        +  where np.int64(198) = _count_waves(_System(system=Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True\nQobj data =\n[[ 1.  0...': False, 'init_pulse_type': 'TRIANGLE', 'fid_err_targ': 1e-05, 'dyn_type': 'UNIT', 'init_pulse_params': {'freq': 20}}))
E        +  and   10 = <test_control_pulseoptim.TestPeriodicControlFunction object at 0x7f7808e8a510>.evo_time

tests/test_control_pulseoptim.py:639: AssertionError
__________________ TestPeriodicControlFunction.test_frequency[20-saw] ___________________

self = <test_control_pulseoptim.TestPeriodicControlFunction object at 0x7f7808e8a850>
pulse_type = 'SAW', frequency = 20

    @pytest.mark.parametrize("frequency", [0.1, 1, 10, 20])
    def test_frequency(self, pulse_type, frequency):
        kwargs = {
            "num_tslots": self.num_tslots,
            "evo_time": self.evo_time,
            "init_pulse_type": pulse_type,
            "init_pulse_params": {"freq": frequency},
            "fid_err_targ": 1e-5,
            "gen_stats": False,
        }
        system = _merge_kwargs(hadamard, kwargs)
>       assert _count_waves(system) == self.evo_time * frequency
E       AssertionError: assert np.int64(199) == (10 * 20)
E        +  where np.int64(199) = _count_waves(_System(system=Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True\nQobj data =\n[[ 1.  0...stats': False, 'init_pulse_type': 'SAW', 'fid_err_targ': 1e-05, 'dyn_type': 'UNIT', 'init_pulse_params': {'freq': 20}}))
E        +  and   10 = <test_control_pulseoptim.TestPeriodicControlFunction object at 0x7f7808e8a850>.evo_time

tests/test_control_pulseoptim.py:639: AssertionError
=================================== warnings summary ====================================
../../../local/bli/conda/test/lib/python3.11/site-packages/qutip/__init__.py:24
  /local/bli/conda/test/lib/python3.11/site-packages/qutip/__init__.py:24: UserWarning: matplotlib not found: Graphics will not work.
    warnings.warn("matplotlib not found: Graphics will not work.")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
```
QuTiP Version:      5.1.0.dev0+418e338
Numpy Version:      2.0.0
Scipy Version:      1.13.1
Cython Version:     None
Matplotlib Version: 3.9.0
Python Version:     3.12.3
Number of CPUs:     40
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

### PR DESCRIPTION
**Pull request by BoxiLi**
fix https://github.com/qutip/qutip-qtrl/issues/26

Would be nice to make another release to include this and #25 because qutip-qip test is failing (https://github.com/qutip/qutip/pull/2504).

### CODE REVIEW

**Review by hodgestar — APPROVED** [review]
The changes here all look fine but I'm not sure after reading the change and the issue what exactly is being fixed.

**Comment by BoxiLi** [comment]
Sorry, should have been clearer here. The test is counting the number of periods by counting the sign flipping in the sampled numpy array. But the sampling number was not large enough. For some unknown reason this did not trigger an error in the previous numpy but now shows up.

**Comment by hodgestar** [comment]
I'm worried that the counting error actually masks some other issue elsewhere. It looks like there were ten samples per period which should be enough to pick up all the sign flips so why were more samples suddenly needed? Can you compare the signals generate in the 1000 and 3000 cases and see what they look like?

**Comment by BoxiLi** [comment]
I don't think visually it makes a difference. I guess it might have to do with how 0.0 or some small numerical inaccuracies are handled in numpy.

numpy=2, sampling point=1000, assertion fails
image

numpy=1.26, sampling point=1000, pass
image

numpy=2, sampling point=3000, pass
image

numpy=1.26, sampling point=3000, pass
image

**Comment by BoxiLi** [comment]
I think it must be some numerical inaccuracy, both `num_tslots = 999` and num_tslots = `1_001` passed. But not `num_tslots = 1_000`.

**Comment by BoxiLi** [comment]
In NumPy 2 the pulse has an exact 0, `pulse[25]==0.`, which is `1.341104507446289e-07` in NumPy 1...
And the test uses `zero_crossings = pulse[0:-2] * pulse[1:-1] < 0` to count, so one point goes missing. Ideally we should use some prime number to avoid this thing I guess.

**Review by hodgestar — APPROVED** [review]

**Pull request merged**
