### PR TITLE
fixed init, start, and update calls for BaseProgressBar

### PR DESCRIPTION
**Pull request by flowerthrower**

### CODE REVIEW

**Review by hodgestar — APPROVED** [review]
Looks good. Will merge once the CI runs pass.

**Comment by hodgestar** [comment]
@flowerthrower Before I merge, how did you pick these up? Are we missing unit tests for these functions?

**Comment by flowerthrower** [comment]
Running pytest on my local device triggered the error in `test_grape.py`.
However as far as I can tell the same test should be executed during the CI checks.
I am not sure why this did not raise an error before.

**Comment by flowerthrower** [comment]
Perhaps the signature changes to `BaseProgressBar` were made after the last PR (which happened 4mo ago).

**Comment by hodgestar** [comment]
> Perhaps the signature changes to `BaseProgressBar` were made after the last PR (which happened 4mo ago).

That seems quite likely. Thanks for fixing!

**Pull request merged**
