### PR TITLE
Compatibility with numpy 2.0

### PR DESCRIPTION
**Pull request by BoxiLi**
There are several compatibility issue with Numpy 2.0. I fixed some of them but have trouble with the rest of the failing tests. Help needed. @pmenczel @hodgestar

### CODE REVIEW

**Comment by BoxiLi** [comment]
Hmmm, to my surprise the action tests raise no error. Locally I do see

```
FAILED tests/test_control_pulseoptim.py::TestPeriodicControlFunction::test_number_of_waves[100-triangle] - AssertionError: assert np.int64(98) == 100
FAILED tests/test_control_pulseoptim.py::TestPeriodicControlFunction::test_frequency[10-triangle] - AssertionError: assert np.int64(98) == (10 * 10)
FAILED tests/test_control_pulseoptim.py::TestPeriodicControlFunction::test_frequency[20-triangle] - AssertionError: assert np.int64(198) == (10 * 20)
FAILED tests/test_control_pulseoptim.py::TestPeriodicControlFunction::test_frequency[20-saw] - AssertionError: assert np.int64(199) == (10 * 20)
```

```
QuTiP Version:      5.1.0.dev0+418e338
Numpy Version:      2.0.0
Scipy Version:      1.13.1
Cython Version:     None
Matplotlib Version: 3.9.0
Python Version:     3.12.3
Number of CPUs:     40
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

**Review by hodgestar — APPROVED** [review]
Changes look good.

Since tests are passing, perhaps let's merge this and investigate any other issues in a follow up MR / issue?

**Comment by hodgestar** [comment]
> FAILED tests/test_control_pulseoptim.py::TestPeriodicControlFunction::test_number_of_waves[100-triangle] - AssertionError: assert np.int64(98) == 100

It's a bit hard to see how getting different numbers (98 and 100) can be a numpy 2 issue, but perhaps it still is somehow?

**Comment by BoxiLi** [comment]
I realize now why the test passed... The numpy version was forced to be <2.0 in the test. But this is not added to the package setup.cfg. So if one installs `qutip-qtrl` now. The package is not usable.

**Pull request merged**
